### ISSUE TITLE
mksyscall question

### ISSUE THREAD

**Issue by albenik** [bugst/go-serial#25]
Why do you using local `mksyscall_windows.go` instead of `$GOROOT` one?

For example look to https://github.com/golang/sys/blob/master/windows/registry/mksyscall.go: `//go:generate go run $GOROOT/src/syscall/mksyscall_windows.go -output zsyscall_windows.go syscall.go`

**Comment by cmaglie** [comment]
Hi @albenik,

no particular reason, just I didn't thought about using `$GOROOT`, it looks like a nice way to remove the `extras` folder.
I'm wondering if this works on windows too? I know that windows use `%VAR%` syntax instead of `$VAR`, but probably this is not a problem under cygwin or msys. Maybe you already tried it? If it works I'll definitely adopt this standard, of course if you want to make a pull request you're welcome :-)

**Comment by albenik** [comment]
`$VAR` syntax in go files are common for all os.
Last fix https://github.com/bugst/go-serial/pull/34
